name: ec_validations
description: A library for validating Ecuadorian identification documents (ID card and RUC).
version: 0.0.9
homepage: https://github.com/JaviKo500
repository: https://github.com/JaviKo500/ec_validations
issue_tracker: https://github.com/JaviKo500/ec_validations/issues
topics:
  - ecuador
  - dni
  - ruc
  - validator
  - cedula

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
